# YAML file for experiments
exp_id: null
experiment: Experiments.ExperimentMod
map_dir: '~/work/clipper/models/rl/GridworldMaps/'
domain: Domains.RCCarBarriersInverted
domain_params:
#     mapname: '12x12-Bridge.txt'
    noise: 0.1
    random_start: False
    # angle: 3.1415 # pi / 2
    wall_array: 
        -   [-0.5, -2, 0.2, 2.5] #bottom left corner
        # -   [0.5, -2, 0.2, 2]
representation: Representations.MahaRBF
representation_params:
#     # domain is implicit as defined above
    resolution_max: 20
    resolution_min: 20
    const_feature: False
    normalize: True
    include_border: True
    # state_dimensions:
        # - 0
        # - 1
        # - 3
    # grid_bins: 
    #     - 8
    #     - 8
    #     - 3
    #     - 8
    num_rbfs: 2000
    seed: null
policy: Policies.DynamicsConfidenceGreedy
policy_params:
    # representation: also implicit
    epsilon: 0.
agent: Agents.NoopAgent
agent_params:
    # - representation
    # - policy
    # - discount factor = domain.discount_factor = 0.9
    initial_learn_rate: 0.9
    lambda_: 0.7
    learn_rate_decay_mode: 'boyan'
    boyan_N0: 2000
max_episode: 1000
max_steps: -1
num_policy_checks: 10
checks_per_policy: 10
